### ISSUE TITLE
Milestone updates

### ISSUE THREAD

**Issue by ASidorenkoCode** [ASidorenkoCode/Kenshins-Journey#21]
- [x] healthbar
- [x] healthbar enemy (if first time hitted)
- [x] jump slash animation
- [x] fall slash animation
- [x] player damage logic
- [x] attack animation enemy (AI for enemy to see player and attack him)
- [x] player pushback logic if hit by enemy
- [x] player death animation
- [x] death animation enemy
- [x] highscore top right corner 
- [x] add highscore if enemy is killed
- [x] show highscore on loadingScreen
- [x] death screen
- [x] load game and save game logic + UI
- [x] level completed screen + show gained highscore points + multiplier -> if no dmg received highscore x2 for example + show option to save game

player stats

- [x] damage
- [x] defense
- [x] movementSpeed
- [x] jumpHeight
- [x] (luck)
